<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="ReleaseProjects.props" Condition="Exists('ReleaseProjects.props')" />
  <Import Project="../ReleaseProjects.props" Condition="!Exists('ReleaseProjects.props')" />
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>14.0</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="$(ReleasePackageNames)" Version="$(SmokePackageVersion)" />
  </ItemGroup>
</Project>
